#include "GUI.h"
#include <iostream>
#include <exception>

int main(int argc, char* argv[]) {
    try {
        std::cout << "Starting RAGger GUI Application..." << std::endl;
        
        // Create GUI application
        Ragger::GUI::GUIApplication app;
        
        // Initialize the application
        if (!app.initialize()) {
            std::cerr << "Failed to initialize GUI application" << std::endl;
            return 1;
        }
        
        // Load a sample file if provided
        if (argc > 1) {
            app.loadFile(argv[1]);
        } else {
            // Load default content
            app.loadFile("main.cpp");
        }
        
        // Set sample prompt content
        app.setPromptContent("// Sample prompt content\n// This would be generated by RAGger");
        
        // Set callbacks
        app.setCodeSelectionCallback([](const CodeBlock& block) {
            std::cout << "Code block selected: " << block.name << std::endl;
        });
        
        app.setPromptGeneratedCallback([](const std::string& prompt) {
            std::cout << "Prompt generated with " << prompt.length() << " characters" << std::endl;
        });
        
        // Run the application
        app.run();
        
        std::cout << "RAGger GUI Application finished" << std::endl;
        return 0;
        
    } catch (const std::exception& e) {
        std::cerr << "Exception in GUI application: " << e.what() << std::endl;
        return 1;
    } catch (...) {
        std::cerr << "Unknown exception in GUI application" << std::endl;
        return 1;
    }
}
